
[theme]
primaryColor = "#6C757D"                 # Cor cinza dos botões/filtros atrativos
secondaryBackgroundColor = "#839e9d"    # Cor de fundo da sidebar (verde)
backgroundColor = "#bee6e4"             # Cor de fundo da área principal
textColor = "#212529"                   # Cor do texto
