
[theme]
primaryColor = "#6C757D"                 # Cor cinza dos botões/filtros atrativos
secondaryBackgroundColor = "#E8F5E9"    # Cor de fundo da sidebar (verde)
backgroundColor = "#FFFFFF"             # Cor de fundo da área principal
textColor = "#212529"                   # Cor do texto
