
[theme]
primaryColor = "#6C757D"                 # Cor cinza dos botões/filtros atrativos
secondaryBackgroundColor = "#fffafa"    # Cor de fundo da sidebar (verde)
backgroundColor = "#ffffff"             # Cor de fundo da área principal
textColor = "#212529"                   # Cor do texto
